### ISSUE TITLE
dateCategory is not a function

### ISSUE THREAD

**Issue by strdr4605** [nagolyhprum/date-category#1]
Tried your package with RunKit and on the local machine but I am getting this error
![image](https://user-images.githubusercontent.com/16056918/49929813-0a09d480-fecc-11e8-8cf1-ec3234219f03.png)
![image](https://user-images.githubusercontent.com/16056918/49929795-feb6a900-fecb-11e8-9015-a67d6da903b0.png)
Maybe because of using 
```javascript
let dateCategory = require('date-category');
```

**Comment by sesn** [comment]
@strdr4605 , If U r using 'require', pls add 'default' since the 'date-category' is exported as default. 

```js
let dateCategory = require('date-category').default;
```

@nagolyhprum , It would be better to add this in readme.md
