### ISSUE TITLE
Ignore files that are not  required for the package 

### ISSUE THREAD

**Issue by strdr4605** [nagolyhprum/date-category#2]
Your package has a lot of files that are not mandatory for the functionality of the package.
![image](https://user-images.githubusercontent.com/16056918/49930402-32460300-fecd-11e8-864d-b8648099a4ed.png)
You can add this
```JSON
"files": [
    "dist/index.js"
  ]
```
to the `package.json` and this will minimize the package size

**Comment by nagolyhprum** [comment]
Resolved here, thanks https://github.com/nagolyhprum/date-category/pull/4
